<?php

function mementos_feelgood_getattributes(){
	$attributes = array();
	$attributes[]=array("name"=>"Action Sequencer","description"=>"This person knows how to set up a jaw-dropping action scene. Lights, camera, AWESOME!");
	$attributes[]=array("name"=>"Ad-lib Mad Lips","description"=>"This contestant is never prepared, and never needs to be!");
	$attributes[]=array("name"=>"Always the Altruist","description"=>"So generous they'll give you the shirt off their back. And their trousers, if you ask nicely.");
	$attributes[]=array("name"=>"Artful Analyst","description"=>"They've got you read like a book, and they KNOW what did you do with the bodies.");
	$attributes[]=array("name"=>"Awesomely Organized","description"=>"When you want something done but don't know where to start, this contestant keeps a cool head and get everything sorted.");
	$attributes[]=array("name"=>"BRAAAAINS","description"=>"Exemplar of the Zombie race. Stagger on, friend!");
	$attributes[]=array("name"=>"Brilliant Buffoon","description"=>"Sultan of Slapstick. Classiest of Clowns. Gives silliness a bright, bright sheen.");
	$attributes[]=array("name"=>"Calm and Still","description"=>"This contestant shows a Zen-like ability to keep their head while all around them are losing theirs.");
	$attributes[]=array("name"=>"Cool Cat","description"=>"pretty fly for a fictitious guy.");
	$attributes[]=array("name"=>"Creative Genius","description"=>"This contestant has all the best ideas, and knows what to do with them.");
	$attributes[]=array("name"=>"Chronic Chrononaut","description"=>"To this contestant, new days are just a blur.");
	$attributes[]=array("name"=>"Cute Butt","description"=>"Sometimes it's just gotta be said.");
	$attributes[]=array("name"=>"Daredevil","description"=>"Point them in the direction of the impossible!");
	$attributes[]=array("name"=>"Dark Horse","description"=>"This contestant has hidden depths that you'll only find by being close to them.");
	$attributes[]=array("name"=>"Dashing Romantic","description"=>"This contestant goes beyond flowers and chocolates - but we're not ones to kiss and tell.");
	$attributes[]=array("name"=>"Delightfully Mad","description"=>"Some contestants are completely bonkers, and this one is bonkers in a good way.");
	$attributes[]=array("name"=>"Dependable Friend","description"=>"Need a place to crash, a drink to quench your thirst, a bandage in that hard-to-reach spot? You know who to call.");
	$attributes[]=array("name"=>"Derring Doer","description"=>"Displaying daring deeds in desperate disasters, a defender of all damsels in distress.");
	$attributes[]=array("name"=>"Diabolical Dialect","description"=>"You can't always tell what this contestant is saying, but they're good at saying it!");
	$attributes[]=array("name"=>"Diplomatic Tongue","description"=>"Can make flinging yourself into an overrun Outpost with naught but a spork and frilly pink panties seem like a good idea.");
	$attributes[]=array("name"=>"Enchanting Entrant","description"=>"Someone who, no matter what the place, time, or scene, makes themself known in an unforgettable manner.");
	$attributes[]=array("name"=>"Eye for Detail","description"=>"remembers if that mutant used its middle, left or back hand the most even with a ten-second glance.");
	$attributes[]=array("name"=>"Exquisite Courtesy","description"=>"Always polite, no matter what.");
	$attributes[]=array("name"=>"Extra Bits","description"=>"Exemplar of the Mutant race. Just keep your noodly appendages to yourself, please. And your poetry.");
	$attributes[]=array("name"=>"Fearless Leader","description"=>"The one you follow, if only out of curiosity.");
	$attributes[]=array("name"=>"Fiery Passion","description"=>"Trust your feelings.");
	$attributes[]=array("name"=>"Fuzzball","description"=>"Exemplar of the Kittymo-ooh, something shiny!");
	$attributes[]=array("name"=>"Gentle Ear","description"=>"Tell me what's wrong.");
	$attributes[]=array("name"=>"Gracious Host","description"=>"This contestant runs an excellent house.");
	$attributes[]=array("name"=>"Gratuitously Geeky","description"=>"For the super smart, or the cognitively crazed.");
	$attributes[]=array("name"=>"Green Eyes","description"=>"Exemplar of the Joker race. Game of cards, anyone?");
	$attributes[]=array("name"=>"Helping Hand","description"=>"Having a hard time? They'll be around shortly.");
	$attributes[]=array("name"=>"Honourable Genteel","description"=>"Most impeccable in eloquence and dress.");
	$attributes[]=array("name"=>"Improbably Successful","description"=>"Don't tell them the odds.");
	$attributes[]=array("name"=>"Inimitable Style","description"=>"There can only be one, and this is them.");
	$attributes[]=array("name"=>"Ingenious Inventor","description"=>"You've gotta wonder where this contestant gets those wonderful toys...");
	$attributes[]=array("name"=>"Innit?","description"=>"Exemplar of the Midget race. Best kept at arm's length.");
	$attributes[]=array("name"=>"Inspiring Force","description"=>"A mover and a shaker. When they're around, others are moved to action.");
	$attributes[]=array("name"=>"Irresistible Charm","description"=>"A smile, a well-timed comment, even a look is all it takes them to befriend you.");
	$attributes[]=array("name"=>"Jack-of-All-Trades","description"=>"Master of fun.");
	$attributes[]=array("name"=>"Knowledge Bank","description"=>"Got a question? They've got answers.");
	$attributes[]=array("name"=>"Life of the Party","description"=>"If they're here, you know things are going to be fun.");
	$attributes[]=array("name"=>"Lovable","description"=>"you don't know what's so great in them, but you can't stop the fuzzy feelings.");
	$attributes[]=array("name"=>"Mad Scientist","description"=>"Mad, I tell you! MAD!");
	$attributes[]=array("name"=>"Master Builder","description"=>"A frequent guest at Dwelling-raisings.");
	$attributes[]=array("name"=>"Metal and Glass","description"=>"Exemplar of the Robot race. Initializing bonus.");
	$attributes[]=array("name"=>"Modest but Awesome","description"=>"Refuses to acknowledge their amazing-ness.");
	$attributes[]=array("name"=>"Mood Lifter","description"=>"Brings smiles where frowns sat before.");
	$attributes[]=array("name"=>"Mostly Harmless","description"=>"Exemplar of the Human race. Welcome, by the way.");
	$attributes[]=array("name"=>"Naughty but Nice","description"=>"There's a heart of gold in there.");
	$attributes[]=array("name"=>"Open Mind","description"=>"But not so open their brains fall out.");
	$attributes[]=array("name"=>"Plotter Extraordinaire","description"=>"They're twelve moves ahead already.");
	$attributes[]=array("name"=>"Poetical Bent","description"=>"Rhymes galore, couldn't ask for more!");
	$attributes[]=array("name"=>"Pungeoneer","description"=>"Taking puns to new heights (or depths, depending on who you ask).");
	$attributes[]=array("name"=>"Quantum Quizzler","description"=>"You can bamboozle even the Cryptic Question Joker.");
	$attributes[]=array("name"=>"Quietly Brilliant","description"=>"Doesn't say much, but when they do, everyone listens.");
	$attributes[]=array("name"=>"Refreshingly Sane","description"=>"In a place where everyone's off their rocker, they are regularly on it. And it's nice.");
	$attributes[]=array("name"=>"Resourceful Roleplayer","description"=>"Supplied by the contents of monsters' pockets and stomachs, this contestant's motto is \"waste not, want not.\"");
	$attributes[]=array("name"=>"Resourceful Repairer","description"=>"Also known as the Fix-It Contestant.");
	$attributes[]=array("name"=>"Scatterbrain","description"=>"Uhmm, sorry, who are you again? I'm su-oh, mum! Hello mum!");
	$attributes[]=array("name"=>"Social Pioneer","description"=>"They've invented the newest craze. Twice.");
	$attributes[]=array("name"=>"Speedy Climber","description"=>"Wait, didn't you just get here?");
	$attributes[]=array("name"=>"Stand-Up Comic","description"=>"Always ready with wit and quips.");
	$attributes[]=array("name"=>"Storyteller","description"=>"Let me tell you a story about the Island.");
	$attributes[]=array("name"=>"Technical Tenacity","description"=>"Practice makes perfect.");
	$attributes[]=array("name"=>"Typo-gremlin Target","description"=>"\"What?! I have fat fingers\"and hilarity ensues.");
	$attributes[]=array("name"=>"Unassuming Artist","description"=>"Look! I drew you a picture! Do you like it?");
	$attributes[]=array("name"=>"Unintentional Wit","description"=>"Oh? That was funny? I didn't mean for it to be, but okay!");
	$attributes[]=array("name"=>"Veteran","description"=>"They've been here FOREVER.");
	$attributes[]=array("name"=>"Voice of Reason","description"=>"A ground wire in the electrical circuits of havoc that are the Island.");
	$attributes[]=array("name"=>"Warm Heart","description"=>"Kind, caring, willing to help, and always sympathetic.");
	$attributes[]=array("name"=>"Welcome Wagon","description"=>"Greetings!");
	$attributes[]=array("name"=>"Witty Wordsmith","description"=>"Parodies, puns, jokes, stories, all fall into their domain.");
	$attributes[]=array("name"=>"Xenophilic","description"=>"One race? That's boring!");
	$attributes[]=array("name"=>"Yard Decorator","description"=>"They make Dwellings pretty.");
	return $attributes;
}
?>